export const COLOR = {
  HEADER_BG_GRADIENT_LEFT: '#fba194',
  HEADER_BG_GRADIENT_RIGHT: '#f6416c',
  HEADER_SEARCHBAR_BG: '#fdfdfd',
  HEADER_DIVIDELINE: '#e8e7eb',
  HEADER_SEARCHBAR_INPUT_FONT: '#0000003d',
  HEADER_SEARCHBAR_SUBMIT_BG: '#f7456e',
};
