export const COLOR = {
  WHITE: '#fff',
  DARK: '#3A3A3A',
  MY_GROUP_BG: '#F4F5FF',
  MY_GROUP_BTN_BG: '#EAECFC',
  MY_GROUP_BTN_HOVER: '#E0E4FF',
  MY_GROUP_BTN_FONT: '#738DFA',
  MY_GROUP_BOX_BG: '#F7E9EC',
};
