export const COLOR = {
  WHITE: '#fff',
  DARK: '#3A3A3A',

  MY_GROUP_BG: '#F4F5FF',
  MY_GROUP_BTN_BG: '#EAECFC',
  MY_GROUP_BTN_HOVER: '#E0E4FF',
  MY_GROUP_BTN_FONT: '#738DFA',
  MY_GROUP_BOX_BG: '#F7E9EC',

  HEADER_BG_GRADIENT_LEFT: '#fba194',
  HEADER_BG_GRADIENT_RIGHT: '#f6416c',
  HEADER_SEARCHBAR_BG: '#fdfdfd',
  HEADER_DIVIDELINE: '#e8e7eb',
  HEADER_SEARCHBAR_INPUT_FONT: '#0000003d',
  HEADER_SEARCHBAR_SUBMIT_BG: '#f7456e',
};
